### ISSUE TITLE
Implement Document Get

### ISSUE THREAD

**Issue by polyfractal** [polyfractal/sherlock#17]

**Comment by jheys** [comment]
i've implemented this in [my fork](https://github.com/jheys/sherlock), if you'd like to grab that

**Comment by polyfractal** [comment]
Great, thanks!  If you can separate it into a PR, I'll merge it straight away.  If that's too hard to separate out I'll just c/p the code a little later today when I get a chance.

**Comment by jheys** [comment]
done. i also included an enhancement to the "kinda gross" final result handling. if you'd rather not include that, let me know and i'll pull that out

**Comment by polyfractal** [comment]
Yeah, I was eyeing that section too.  I like it, definitely less gross :)

Good catch with the PHP version number, didn't realize that was a bug in earlier 5.3 versions.
