### ISSUE TITLE
Implement Document Update

### ISSUE THREAD

**Issue by polyfractal** [polyfractal/sherlock#18]

**Comment by Mopster** [comment]
Am I correct to assume that at this moment it is not possible to update a document in the index ? So in order to update any document, I need to recreate the index ? Is there a timeframe of this implementation ? Quite important for big indexes. :-)

**Comment by polyfractal** [comment]
Yeah, that's correct =/

I'll try to get an initial version working today or tonight.  Should be relatively easy to implement.

**Comment by Mopster** [comment]
Sounds good, then I can implement it tomorrow :-) Refactoring my own bundle now, updating documents will be a welcome addition :-)

**Comment by polyfractal** [comment]
Few things.  First, I forgot entirely that Sherlock already supports document overwriting.  So if you have the source and just want to overwrite the entire document, this works:

``` php
//Insert a doc, specifying the ID of "123"
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(array("field" => "test"), 123);
$response = $doc->execute();

//Insert another doc using the same ID...this overwrites the first
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(array("new_field" => "abc"), 123);
$response = $doc->execute();
```

If you don't want to overwrite, I just pushed some code changes to allow actual updates.  The code is in Master, but not as a release yet because the code is really kludgy, I'm not at all happy with how it works internally.  The way I implemented batch processing has made working with normal documents like this very difficult.  

I'm going to nuke the code and refactor it, but in the mean time, you can do this to update:

``` php
 //First insert a doc, specifying the ID of "456"
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(array("field" => "test"), 456);
$response = $doc->execute();

//Then update with a partial document.
//Notice how the document has new fields/values, and "true" is passed as a third parameter
//This utilizes ES's "partial document update" mechanism
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(array("field2" => "test2"), 456, true);
$response = $doc->execute();
```

You can also use scripts/parameters to update:

``` php
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(array("field" => "test"), 789);
$response = $doc->execute();

//This syntax is pretty gross...sorry
//You still have to specify a document, but pass a null doc value, the ID and "true" for update
//Then you can set the updateScript and updateParams
$doc = $sherlock->document()->index('testindexing')
                           ->type('tweet')
                           ->document(null,789,true)
                           ->updateScript('ctx._source.field += tag')
                           ->updateParams(array("tag" => 'blue'));
$response = $doc->execute();
```

Caveat: updates do not currently work the documents() method, where you provide an array of raw Commands, or with a custom BatchInterface.

Like I said, not pleased with how this came out, but it should work in the mean time until I can get a more elegant solution put together.

Very little testing on these new features, so as always let me know if you run into problems :)

**Comment by Mopster** [comment]
I was looking for the possibility of the first option, but couldn't find any code that would support it. Seems like I missed it. The document overwriting will do at this moment and it works (just tested it). We will possibly use the real document update feature in the future when we plan to have a big index to worry about.

**Comment by polyfractal** [comment]
Cool cool, hopefully I'll have a better interface by time you need the Updates :)
