### ISSUE TITLE
fuzziness(0) ≠ fuzziness(null)

### ISSUE THREAD

**Issue by chadkouse** [polyfractal/sherlock#2]
to disable fuzziness on a match you have to use fuzziness(null) when fuzziness(0) should work.

![Screen Shot 2013-03-07 at 1 52 46 PM](https://f.cloud.github.com/assets/284226/233614/4b21be0a-875a-11e2-9088-2721486025a0.png)

Top test was run with fuzziness(0) and bottom test was run with fuzziness(null)

``` php
$query = sherlock::query()->bool()->must(array(
            sherlock::query()->match()->field("artist_name.lower")->query($artist)->fuzziness(0),
            sherlock::query()->term()->field("type")->term("Album"),
            sherlock::query()->match()->field("typeCount")->query(1)
        ));
```

``` php
$query = sherlock::query()->bool()->must(array(
            sherlock::query()->match()->field("artist_name.lower")->query($artist)->fuzziness(null),
            sherlock::query()->term()->field("type")->term("Album"),
            sherlock::query()->match()->field("typeCount")->query(1)
        ));
```

**Comment by chadkouse** [comment]
this could very well not be a sherlock issue since the query json looks fine....

**Comment by chadkouse** [comment]
Not a code issue, just a documentation issue.

> I'll make a note in the docs about using null to disable (or add a disableFuzziness() method). Thanks!

**Comment by polyfractal** [comment]
Looks like it is indeed a Sherlock bug - I have the default fuzziness value set incorrectly.  Fuzziness should be set to null explicitly by default.

ElasticSearch is looking for the presence or absence of the "fuzziness" field to determine fuzzy behavior.  If it is absent (or explicitly set to null), the Match acts in a non-fuzzy manner.  If the field is specified, it converts into fuzzy mode.

Proof of what ES is doing:

This JSON blob derived from the first Bool query:

``` json
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "artist_name.lower": {
              "query": "Coldplay",
              "boost": 1,
              "operator": "and",
              "analyzer": "default",
              "fuzziness": 0,
              "lenient": true,
              "max_expansions": 100,
              "minimum_should_match": 2,
              "prefix_length": 2
            }
          }
        },
        {
          "term": {
            "type": {
              "value": "Album"
            }
          }
        },
        {
          "match": {
            "typeCount": {
              "query": 1,
              "boost": 1,
              "operator": "and",
              "analyzer": "default",
              "fuzziness": 0.5,
              "lenient": true,
              "max_expansions": 100,
              "minimum_should_match": 2,
              "prefix_length": 2
            }
          }
        }
      ],
      "must_not": [],
      "should": [],
      "minimum_number_should_match": 2,
      "boost": 1,
      "disable_coord": 1
    }
  }
}
```

is parsed into this lucene query inside of ES:

```
+artist_name.lower:coldplay~0 +type:Album +typeCount:1~0.5
```

Conversely, if you omit the fuzziness field entirely, you get this query:

```
+artist_name.lower:coldplay +type:Album +typeCount:1
```

ES drops the tilde values from the query, which means it is no longer utilizing a fuzzy match

**Comment by chadkouse** [comment]
I've noticed something similar with the "analyzer" property.  If you use the default "default" analyzer you get different results than if you omit analyzer or explicitly set it to null.  Consequently I'm setting it to null quite a bit.  Want a separate issue? 

-- chad

**Comment by polyfractal** [comment]
Yeah, open up another issue if you get a chance.  I'm guessing it's a similar problem...I'll look into it later tonight.  Thanks!
