### ISSUE TITLE
Allow raw queries to be standalone raw

### ISSUE THREAD

**Issue by thireven** [polyfractal/sherlock#22]
Right now, a raw query is wrapped around a "query" field: {"query":{your_raw_query}}, which doesn't allow for the complexity that you would need to use a raw query to begin with. For example:

``` json
{
    "query": {
        "match": {
            "name": {
                "query": "Some query",
                "operator": "or"
            }
        }
    },
    "indices_boost": {
        "index1": 1.4,
        "index2": 1.3
    }
}
```

Made the appropriate modification for my purposes here:
https://github.com/thireven/sherlock/commit/e02c43042686eec9f9cc839851972a6af0cf75f4

**Comment by polyfractal** [comment]
Yep, that makes more sense =)

Send a pull request and I'll merge it, otherwise I'll get around to it later tonight.  Thanks!
