### ISSUE TITLE
TermQuery returns all results

### ISSUE THREAD

**Issue by Mopster** [polyfractal/sherlock#25]
Hello,

We've decided on using this bundle and I've been trying to build a test to see how it works. I've managed to create and populate an index. But when I'm trying to query it with a TermQuery, I get all the documents as a result instead of only the matching ones. I'm not sure where I did something wrong.

Here's my class

``` PHP
    public function setupIndex()
    {
        $index = $this->sherlock->index('testindex');
        $response = $index->create();

        return $response->ok;
    }

    public function populateIndex()
    {
        $doc = array("firstname" => "Roderik", "lastname" => "van der Veer", "function" => "Technology Director");
        $doc = $this->sherlock->document()->index('testindex')->type('employee')->document($doc);
        $doc->execute();

        $doc = array("firstname" => "Kenny", "lastname" => "Debrauwer", "function" => "Web Developer");
        $doc = $this->sherlock->document()->index('testindex')->type('employee')->document($doc);
        $doc->execute();

        $doc = array("firstname" => "Kurt", "lastname" => "Limbos", "function" => "Art Director");
        $doc = $this->sherlock->document()->index('testindex')->type('employee')->document($doc);
        $doc->execute();
    }

    public function searchIndex()
    {
        $request = $this->sherlock->search();

        $termQuery = Sherlock::queryBuilder()->Term()->field("firstname")->term("Kurt");
        echo $termQuery->toJSON()."\r\n";

        $request->index("testindex")
                ->type("employee")
                ->query($termQuery);
        echo $request->toJSON()."\r\n";

        $response = $request->execute();

        echo "Took: ".$response->took."\r\n";
        echo "Number of Hits: ".count($response)."\r\n";

        foreach($response as $hit)
        {
            return $hit['score'].' : '.$hit['source']['firstname'].' '.$hit['source']['lastname'].' - '.$hit['source']['function']."\r\n";
        }
    }
```

I created commands for each method so I can test them in CLI.

``` bash
$ app/console kuma:search:setup
Index created : 1
$ app/console kuma:search:populate
Index populated
$ app/console kuma:search:search
{"term":{"firstname":{"value":"Kurt"}}}
{"query":{"term":{"firstname":{"value":"Kurt"}}}}
Took: 3
Number of Hits: 3
Index searched
1 : Kenny Debrauwer - Web Developer
1 : Roderik van der Veer - Technology Director
1 : Kurt Limbos - Art Director
Index searched
```

I've tried using the same JSON output with a curl command, but that returns no results : 

``` bash
$ curl -XPOST 'http://127.0.0.1:9200/testindex/employee/_search?pretty=true' -d '{"query":{"term":{"firstname":{"value":"Kurt"}}}}'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

I also tried using Match instead of Term, same result : 

``` PHP
$termQuery = Sherlock::queryBuilder()->Match()->field("firstname")->query("Kurt");
```

``` bash
$ app/console kuma:search:search
{"match":{"firstname":{"query":"Kurt","boost":1,"operator":"and","analyzer":"default","fuzziness":null,"lenient":true,"max_expansions":100,"minimum_should_match":2,"prefix_length":2,"type":null}}}
{"query":{"match":{"firstname":{"query":"Kurt","boost":1,"operator":"and","analyzer":"default","fuzziness":null,"lenient":true,"max_expansions":100,"minimum_should_match":2,"prefix_length":2,"type":null}}}}
Took: 2
Number of Hits: 3
1 : Roderik van der Veer - Technology Director
1 : Kurt Limbos - Art Director
1 : Kenny Debrauwer - Web Developer
Index searched

```

Here's the content of the index (using a wildcard search) : 

``` bash
$ curl -XGET 'http://127.0.0.1:9200/testindex/employee/_search?q=*&pretty=true'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "testindex",
      "_type" : "employee",
      "_id" : "VetaJaMvSESmf1Wkn_lPXA",
      "_score" : 1.0, "_source" : {"firstname":"Kenny","lastname":"Debrauwer","function":"Web Developer"}
    }, {
      "_index" : "testindex",
      "_type" : "employee",
      "_id" : "TdNxF5nmQJusa-FGURiCNQ",
      "_score" : 1.0, "_source" : {"firstname":"Roderik","lastname":"van der Veer","function":"Technology Director"}
    }, {
      "_index" : "testindex",
      "_type" : "employee",
      "_id" : "IfIMzJ_FQWil2gH2kr3DUA",
      "_score" : 1.0, "_source" : {"firstname":"Kurt","lastname":"Limbos","function":"Art Director"}
    } ]
  }
}
```

I followed the Quickstart Guide on the website. 
I also want to report that I can't install v0.1.8 with composer, it's conflicting with the Event Dispatcher. If I use 0.1.\* in my composer, an old version gets installed.

**Comment by polyfractal** [comment]
Hmm, I have a couple ideas.  I'll debug the Composer problem first, since 0.1.8 had a big refactor of the internal transport layer (which may also fix this problem).  I'll keep you updated, hopefully have something to report soonish.

**Comment by Mopster** [comment]
Sounds good. 

I also gave the unit tests a try, but they all succeeded. The QueryTest does not check the returned results, it just checks the querybuilder ?

**Comment by polyfractal** [comment]
Yeah, the tests are really terrible at the moment.  They are on my short-list to give some love, since these kinds of quality control issues slip through them.  Right now the tests only catch syntax issues or outright errors, which as you just saw, misses a lot of problem cases =(

**Comment by polyfractal** [comment]
Quick question:  I'm assuming you are using Symfony?  What version are you using?  I think the composer problem may be related to explicitly defining the Event-Dispatcher version rather than allowing a range with ~ or *, but I want to doublecheck before I push a change.

**Comment by Mopster** [comment]
I'm currently using 2.1.9

**Comment by polyfractal** [comment]
Ok, just pushed v0.1.9.  I relaxed the version requirements for Event-Dispatcher to ~2.1.  The strict requirement for 2.2.0 was making composer downgrade to the most recent version that didn't include Event-Dispatcher.

Try 0.1.9 and let me know if it fixes your query problems, if not I'll start debugging that next.  Thanks for being patient with me...I'm pretty new to Composer versioning  :)

**Comment by Mopster** [comment]
The 0.1.9 now installs with composer. I did git clone before so I was using the latest code. So the problem still remains.

And being patient with someone who starts working on the problem right away is a given ;-)
They asked me for a working prototype of the search (with facets) at the end of the week, so I appreciate the fast response :)

**Comment by polyfractal** [comment]
Oooh, ok.  Ill start working on the query problem then!  =)

**Comment by Mopster** [comment]
If it helps you, I pushed my code here : https://github.com/Kunstmaan/KunstmaanSearchBundle/blob/sherlock/Sherlock/SherlockImpl.php

**Comment by polyfractal** [comment]
Oh boy, found a couple of problems.  I'll put together a fix and push it live in a minute.  Basically:
- Problem with the underlying cURL library that I just integrated, took me a bit to hunt it down since I'm not overly familiar with it's internals yet
- Problem with how I was setting data
- Accidentally double json-encoding the data (doh)

Tangentially related, your query is going to return 0 results because TermQuery is case-sensitive.  Since you are not specifying a mapping, ES will default to the "Standard Analyzer", which lowercases terms.  A TermQuery for "kurt" will find what you want.

**Comment by polyfractal** [comment]
v0.1.10 pushed, hows it look now?

**Comment by Mopster** [comment]
It looks good, it works, thanks. I'll be testing it further tomorrow: mappings, facets, etc...

Meanwhile, I'd also like to point out the links to the Quickstart are broken. I assume the site has undergone an update recently. :-)

**Comment by polyfractal** [comment]
Great!  Facets are a new feature, so they may or may not be working well...just an FYI.

The entire support site is mid-conversion to a new layout with better/more complete docs.  I'm hoping to get it up and online in the next several days.  Sorry about the broken links!

**Comment by Mopster** [comment]
I'll keep an eye on the website, the docs will help. ;-) If I encounter anything else I'll create an issue :-)

**Comment by Mopster** [comment]
I'll close this since this problem has been resolved. I'll open new issues when needed :)
