### ISSUE TITLE
Analyzer field

### ISSUE THREAD

**Issue by Mopster** [polyfractal/sherlock#36]
Is the analyzer field supported ? I think I'll be needing it for my multilingual documents.

http://www.elasticsearch.org/guide/reference/mapping/analyzer-field/

**Comment by polyfractal** [comment]
Nope, not support at the moment.  Just glancing over the mapping structure, I think it should be pretty easy to add (famous last words, heh).

I'll see what I can do after I get some coffee :)

**Comment by polyfractal** [comment]
Just pushed a new version that includes the Analyzer mapping interface.  Usual disclaimer applies: little testing, let me know if it breaks, etc etc 

:)

**Comment by Mopster** [comment]
I get the following error : 

  [Sherlock\common\exceptions\ClientErrorResponseException]  
  MapperParsingException[mapping [page]]; nested: MapperParsingException[No type specified for property [_analyzer]]

``` PHP
        $index->mappings(
            Sherlock::mappingBuilder($this->indexType)->String()->field('parents')->analyzer('keyword'),
            Sherlock::mappingBuilder($this->indexType)->String()->field('ancestors')->analyzer('keyword'),
            Sherlock::mappingBuilder($this->indexType)->String()->field('tags')->analyzer('keyword'),
            Sherlock::mappingBuilder($this->indexType)->String()->field('type')->analyzer('keyword'),
            Sherlock::mappingBuilder($this->indexType)->String()->field('slug')->analyzer('keyword'),
            Sherlock::mappingBuilder($this->indexType)->Analyzer()->path("contentanalyzer")
        );

        $index->create();
```

Do you happen to have any idea what I should add in my "contentanalyzer" field as language analyzer ? "EnglishAnalyzer" or "DutchAnalyzer" or something like that ?

``` PHP
$doc = array(
                        "node_id"               => $node->getId(),
                        "nodetranslation_id"    => $nodeTranslation->getId(),
                        "nodeversion_id"        => $publicNodeVersion->getId(),
                        "title"                 => $nodeTranslation->getTitle(),
                        "lang"                  => $nodeTranslation->getLang(),
                        "slug"                  => $nodeTranslation->getFullSlug(),
                        "type"                  => ClassLookup::getClassName($page),
                        "contentanalyzer"       => "english"
                    );
```

If this works I'd let "contentanalyzer" be different depending on the language of the document.

The web has a serious lack on how-to's concerning ElasticSearch :)

**Comment by polyfractal** [comment]
Gah, I misinterpreted the ES docs.  _analyzer goes under the Type root, not the document root.  Pushed a fix, should work now.

Regarding the language stuff, I'm not positive (never worked with them personally), but I think you specify the analyzer name as it appears here: http://www.elasticsearch.org/guide/reference/index-modules/analysis/lang-analyzer/

So "english", "brazilian", "swedish", etc.

If you make a custom analyzer called "EnglishAnalyzer", then you could specify that too.

**Comment by polyfractal** [comment]
Actually looks like I broke something else, only "slug" is being added to the mapping (none of the other strings).  Looking into it

**Comment by polyfractal** [comment]
Fixed the fix :)

My array merge was clobbering same-named array keys ("properties" of the document).  Switched to array_merge_recursive and things are happy now.

**Comment by Mopster** [comment]
Ok, it works, as in, it isn't broken. I'll need to do some testing to see if it really does use the 'english' or 'dutch' analyzer based on the content of the field. But the mapping is set :-)

**Comment by polyfractal** [comment]
Cool cool, closing this :)
