### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by Mopster** [polyfractal/sherlock#37]
I used the 'from' and 'size' parameter but it doesn't seem to take them into account when returning the search results. Not sure if I can set them to the SearchRequest or if they're part of the query.

Here's my code : 

``` PHP
        $request->index($indexName)->type($indexType)->query($query);

        if($from){
            $request->index($indexName)->type($indexType)->from($from);
        }

        if($size){
            $request->index($indexName)->type($indexType)->size($size);
        }

        $response = $request->execute();
```

$from and $size are both set to 2. The response contains 4 hits instead of only 2 as defined by 'size'.

In my PagerFanta (a pagination bundle) adapter : 

``` PHP
function getSlice($offset, $length)
    {
        $this->response = $this->search->search($this->indexName, $this->indexType, $this->querystring, $this->json, $offset, $length);
        return $this->response['hits']['hits'];
    }
```

**Comment by polyfractal** [comment]
Hmm, I'm having a hard time recreating this bug.  Could you paste the `$request->toJSON()` output so I can look at the raw JSON DSL?  What does your query look like?  ES will sometimes return all results if the query is syntactically correct but nonsensical, or if the wrong HTTP method is used...I may have a bug there instead.

Unrelated, but you could shorten your above snippet to this:

``` php
$request->index($indexName)->type($indexType)->query($query);

if($from){
    $request->from($from);
}

if($size){
    $request->size($size);
}

$response = $request->execute();
```

**Comment by Mopster** [comment]
I changed to the above code.

This is the $request->toJSON() : 

```
{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"*","boost":1}}},{"wildcard":{"content":{"value":"*","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["<strong>"],"post_tags":["<\/strong>"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}}
```

When debugging I see the SearchRequest "params" has "size = 2" and "from=2", but they seem to be missing in the JSON

**Comment by polyfractal** [comment]
Still can't recreate it.  What version of Sherlock are you using? Its strange that you can see the size/from parameters, but nothing in the JSON output.  I'm pretty stumped :(

Here is my test code, which is pretty close to your JSON output:

``` php
$indexName = 'testqueries';
        $indexType = 'test';
        $from = 2;
        $size = 2;

        $request = $this->object->search();

        $wildcard = Sherlock::queryBuilder()->Wildcard()->field("title")->value("*");
        $query = Sherlock::queryBuilder()->Bool()->should($wildcard, $wildcard);

        $facet = Sherlock::facetBuilder()->Terms()->fields("tags")->facetname("tag");
        $facet2 = Sherlock::facetBuilder()->Terms()->fields("type")->facetname("type");
        $highlight = Sherlock::highlightBuilder()->Highlight()->pre_tags(array("<strong>"))->post_tags(array("</strong>"))->fields(array("content" => array()));

        $request->index($indexName)->type($indexType)->query($query)->facets($facet, $facet2)->highlight($highlight);

        if($from){
            $request->from($from);
        }

        if($size){
            $request->size($size);
        }
```

And the output from that, which includes from/size:

``` json
{
   "query":{
      "bool":{
         "must":[

         ],
         "must_not":[

         ],
         "should":[
            {
               "wildcard":{
                  "title":{
                     "value":"*",
                     "boost":1
                  }
               }
            },
            {
               "wildcard":{
                  "title":{
                     "value":"*",
                     "boost":1
                  }
               }
            }
         ],
         "minimum_number_should_match":2,
         "boost":1,
         "disable_coord":1
      }
   },
   "facets":{
      "tag":{
         "terms":{
            "fields":[
               "tags"
            ],
            "order":"count",
            "all_terms":false,
            "size":null,
            "exclude":null,
            "regex":null,
            "regex_flags":null,
            "script":null,
            "script_field":null,
            "params":null,
            "lang":null
         },
         "facet_filter":null
      },
      "type":{
         "terms":{
            "fields":[
               "type"
            ],
            "order":"count",
            "all_terms":false,
            "size":null,
            "exclude":null,
            "regex":null,
            "regex_flags":null,
            "script":null,
            "script_field":null,
            "params":null,
            "lang":null
         },
         "facet_filter":null
      }
   },
   "highlight":{
      "pre_tags":[
         "\u003Cstrong\u003E"
      ],
      "post_tags":[
         "\u003C\/strong\u003E"
      ],
      "number_of_fragments":null,
      "fragment_size":null,
      "fields":[
         {
            "content":[

            ]
         }
      ]
   },
   "from":2,
   "size":2
}
```

**Comment by Mopster** [comment]
Ok, I tracked the problem down to using the Raw query. I switched to using a Boolean query (like above) and it works. When using the Raw query, it probably doesn't take anything else in account.

``` PHP
        $json = $request->toJSON();
        $query = Sherlock::queryBuilder()->Raw($json);
        $request->index($indexName)->type($indexType)->query($query);

        if($from){
            $request->from($from);
        }

        if($size){
            $request->size($size);
        }
```

**Comment by polyfractal** [comment]
Ok, cool.  That makes sense - the Raw query is 100% raw.  It's basically just a glorified curl command, the user is expected to provide the complete JSON.

Sorry, I don't think that is documented anywhere.  Still slogging my way through the documentation when I get free time.

**Comment by Mopster** [comment]
Ok, then I'll have to think on how I can make this work or rethink my plan. Do you plan on altering the way this works to maybe accomodate this ?

**Comment by polyfractal** [comment]
So you need a Raw query (in the ElasticSearch sense of a query, e.g. the "query" : {} portion of the request), not necessarily an entirely raw request?

Would it make sense to have both a Raw Query and a Raw Request?
- Raw Query: specify the raw JSON for the "query" : {}  portion of the request, use the Sherlock functionality for everything else (facets, sort, highlighter, etc)
- Raw Request: 100% raw request, user provides all the JSON

Does that seem more useful?  If it does, it would probably make sense to add a RawFilter, RawHighlighter, etc.

**Comment by Mopster** [comment]
It sounds like a good idea, but you're the expert here :-) Having a the new 'Raw' options would increase the possibilities. Like having some predefined settings (pagination and highlighting) and let the user have full control over the query.

**Comment by Mopster** [comment]
any update ? :-)

**Comment by polyfractal** [comment]
Gah, sorry.  Just got back to the states and have been catching up.  I think its a good idea to have multiple "Raw" queries/requests.  I'll put in the functionality today.  

Thanks for the poke to remind me about this! :)

**Comment by Mopster** [comment]
No problem, we're working on a project with serious deadlines at the moment and it helps knowing the status of everything so we can plan accordingly ;-)

**Comment by polyfractal** [comment]
Ok, so there is a new RawRequest.  You specify the URI, method and body.  Everything else is up to you:

``` php
$req = $sherlock->raw();
$req->uri("testindex/_search")
    ->method("post")
    ->body('{"query":{"match_all":{"boost":0.5}}}');
$response = $req->execute();
```

RawQuery is now "downgraded" to just affecting the "query: {}" portion of the query, meaning it is used in an overall request just like any other query.

There is also a new RawFacet and RawFilter which function similarly.

**Comment by Mopster** [comment]
Using my existing code (https://github.com/Kunstmaan/KunstmaanNodeSearchBundle/blob/master/Entity/AbstractSearchPage.php), I get this query JSON : 

{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"_","boost":1}}},{"wildcard":{"content":{"value":"_","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["\u003Cstrong\u003E"],"post_tags":["\u003C\/strong\u003E"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}}

I add from, size and highlighting here: https://github.com/Kunstmaan/KunstmaanSearchBundle/blob/master/Sherlock/SherlockSearchProvider.php

And using that Raw query I get the following error : 

SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[-RKDImuhR9Om56zgnaxdKw][nodeindex][3]: SearchParseException[[nodeindex][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"_","boost":1}}},{"wildcard":{"content":{"value":"_","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["&lt;strong&gt;"],"post_tags":["&lt;\/strong&gt;"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}},"size":10}]]]; nested: QueryParsingException[[nodeindex] No query registered for [query]]; }{[-RKDImuhR9Om56zgnaxdKw][nodeindex][0]: SearchParseException[[nodeindex][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"_","boost":1}}},{"wildcard":{"content":{"value":"_","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["&lt;strong&gt;"],"post_tags":["&lt;\/strong&gt;"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}},"size":10}]]]; nested: QueryParsingException[[nodeindex] No query registered for [query]]; }{[-RKDImuhR9Om56zgnaxdKw][nodeindex][4]: SearchParseException[[nodeindex][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"_","boost":1}}},{"wildcard":{"content":{"value":"_","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["&lt;strong&gt;"],"post_tags":["&lt;\/strong&gt;"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}},"size":10}]]]; nested: QueryParsingException[[nodeindex] No query registered for [query]]; }{[-RKDImuhR9Om56zgnaxdKw][nodeindex][1]: SearchParseException[[nodeindex][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query":{"bool":{"must":[],"must_not":[],"should":[{"wildcard":{"title":{"value":"_","boost":1}}},{"wildcard":{"content":{"value":"_","boost":1}}}],"minimum_number_should_match":1,"boost":1,"disable_coord":1}},"facets":{"tag":{"terms":{"fields":["tags"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null},"type":{"terms":{"fields":["type"],"order":"count","all_terms":false,"size":null,"exclude":null,"regex":null,"regex_flags":null,"script":null,"script_field":null,"params":null,"lang":null},"facet_filter":null}},"highlight":{"pre_tags":["&lt;strong&gt;"],"post_tags":["&lt;\/strong&gt;"],"number_of_fragments":null,"fragment_size":null,"fields":[{"content":{"fragment_size":250,"number_of_fragments":1}}]}},"size":10}]]]; nested: QueryParsingException[[nodeindex] No query registered for [query]]; }]

**Comment by polyfractal** [comment]
So the parsing error is because "query" is duplicated. My first guess is that the JSON held in $querystring is formatted like

```
"query" :{ "bool": {<etc etc>} }
```

Since a Raw query is now technically a query, you don't need the "query" portion at the beginning:

```
"bool": { <etc etc>}
```

If that isn't the case, then there is a bug that I'm just not seeing...

**Comment by Mopster** [comment]
Ok, I didn't quite get the error. I assumed everything would keep working without changing code, but that was wrong to assume. I found what I had to change in order for it to work. I had to change : 

``` PHP
$request = $this->sherlock->search();
$query = Sherlock::queryBuilder()->Raw($querystring);
$request->index($indexName)->type($indexType)->query($query);
```

to

``` PHP
$request = $this->sherlock->raw();
$request->uri($indexName . "/" . $indexType . "/_search")->method("post")->body($querystring);
```

I'll need to do some more expanding on my code to fully support the new Raw capabilities :-)

**Comment by polyfractal** [comment]
Ok, cool.  Depending on your need, either approach could work.  The first approach is if you want to construct an arbitrary query (in the sense of "query: {}"), but use Sherlock to construct the rest of the DSL (such as adding filters, facets, etc):

``` php
$querystring = '{"term":{"field1":{"value":"town"}}}';

$request = $this->sherlock->search();
$query = Sherlock::queryBuilder()->Raw($querystring);
$filter = Sherlock::filterBuilder()->MatchAll();
$request->index($indexName)->type($indexType)->query($query);
```

yields:

``` json
{"query":{"term":{"field1":{"value":"town"}}},"filter":{"match_all":[]}}
```

The second approach, using the Raw Request, lets you do the entire request in one fell swoop:

``` php
$querystring = '{"query":{"term":{"field1":{"value":"town"}}},"filter":{"match_all":[]}}';

$request = $this->sherlock->raw();
$request->uri($indexName . "/" . $indexType . "/_search")->method("post")->body($querystring);
```
