### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eleshar** [polyfractal/sherlock#48]
I'm trying to access the documentation for Index Operations, Indexing Documents, Search, Errors, but nothing loading on the website under these sections:

http://sherlockphp.com/documentation/index-operations/
http://sherlockphp.com/documentation/indexing-documents/
http://sherlockphp.com/documentation/search/
http://sherlockphp.com/documentation/errors/

Is it available somewhere else?

**Comment by polyfractal** [comment]
Sadly, it is not - I haven't written the docs for it yet.  It's high on my [to-do roadmap](https://github.com/polyfractal/sherlock/blob/master/Roadmap.md), but I just haven't had time yet.  

The integration tests (also a subject needing serious work) show a decent amount of usage examples, for at least basic operations.  There are also some feature issues where I've laid out syntax (search for bulk indexing, for example).

Sorry :(  I desperately want to work on the docs site, but real life is going to be pretty hairy for the next week or so (just got back from vacation, and I'm moving apartments this coming weekend).
