### ISSUE TITLE
Match() query deviates from ElasticSearch default

### ISSUE THREAD

**Issue by kwisatz** [polyfractal/sherlock#53]
Hi, is there a specific reason, why the Match() query has **operator** set to **and** as a default when ElasticSearch sets it to **or**?

> The default match query is of type boolean. It means that the text provided is analyzed and > the analysis process constructs a boolean query from the provided text. The operator flag > can be set to or or and to control the boolean clauses (defaults to or).
> (http://www.elasticsearch.org/guide/reference/query-dsl/match-query/)

**Comment by polyfractal** [comment]
No specific reason...likely just a typo.  

I'm going to leave it alone for now, since the resolution of #30 will take care of the issue (and prevent breaking what people are using in the mean time).
