### ISSUE TITLE
After update my version to last version, a Exception show in my app

### ISSUE THREAD

**Issue by bent0ws** [polyfractal/sherlock#68]
ErrorException [ Strict ]: Declaration of Sherlock\Sherlock::raw() should be compatible with Pimple::raw($id).
23 /**
24  \* Class Sherlock
25  \* @package Sherlock
26  */
27 class Sherlock extends Pimple
28 {

**Comment by polyfractal** [comment]
Did you upgrade to the 0.2 branch?  It is 100% unstable at this point and I don't think it is even functional yet.  I'm still in the middle of rearranging a lot of Sherlock's guts, so things may well be broken.

Stick to the 0.1.\* branch if you need something that actually works :)

**Comment by bent0ws** [comment]
no, I'm use
sherlock/sherlock": "~0.1"

2013/6/27 Zachary Tong notifications@github.com

**Comment by bent0ws** [comment]
probably works now, i change
"sherlock/sherlock": "~0.1"
to
"sherlock/sherlock": "0.1"

2013/6/27 Zachary Tong notifications@github.com

**Comment by bent0ws** [comment]
Cool, it's "works" now, but i get a new problem.. Idon't know why it's
generate this fatal error with version 0.1.13:

PHP Fatal error:  Can't inherit abstract function
Sherlock\components\QueryInterface::toArray() (previously declared
abstract in sherlock\components\BaseComponent) in
/sherlock/sherlock/src/Sherlock/components/queries/QueryString.php on line
19,

referer:

Sherlock::queryBuilder()->Field()->field("name")->query($m)->default_operator("AND");

2013/6/27 Anderson Bento deca.rox@gmail.com

**Comment by polyfractal** [comment]
Gah, I'm not sure.

Can you post the code that constructs `$m` in that query too?

**Comment by bent0ws** [comment]
$m is a simple string;

$m = "nike"; for example.

I don't know if it's help, but when I run the same code in PHP 5.4.6 it's
works, and when I run in PHP 5.3.3  show this error.

2013/6/27 Zachary Tong notifications@github.com

**Comment by polyfractal** [comment]
Interesting...let me look into it and see if its a Sherlock problem or potentially an early 5.3.\* PHP problem.  Thanks!

**Comment by bent0ws** [comment]
5.3.3 was the problem :)

It's works now with 5.3.26

2013/6/27 Zachary Tong notifications@github.com

**Comment by polyfractal** [comment]
Awesome, glad you got it working.

I'm pretty sure it is [related to this issue](https://bugs.php.net/bug.php?id=43200), which was fixed in 5.3.9.  So yeah, a problem with early versions of PHP

**Comment by polyfractal** [comment]
Closing, reopen if you have any further problems! :)
